spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://192.168.1.6:3306/video_db?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 1q2w3e4R!@
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000

base-directory:
  back-video: /home/back/video/ # 视频下载路径
  back-file: /home/back/file/ # 文件下载/上传路径
  hls-video: /home/video-hls/videos/ # m3u8视频下载路径
  ehcache-path: /home/webui/video-platform/ehcache/ # ehcache路径

sign:
  enable: false

q-msg:
  enable: true
  key: q-msg-key

ffmpeg:
  log-level: warning
  hls-time: 60

nginx-config:
  protocol-type:
    local:
      protocol: http
      name: local
      local-ipv4-ip: 127.0.0.1 # 数据库中环回地址
    ipv4:
      name: ipv4
      lan-name: wlan0 # 局域网IPV4网卡
    ipv6:
      name: ipv6
    domain:
      name: domain
      host: domain-host
      api-key: api-key
  m3u8-suffix: http://127.0.0.1:8087/hls/
  mp4-suffix: http://127.0.0.1:8087/back/video/
  gif-suffix: http://127.0.0.1:8087/back/video/
  file-suffix: http://127.0.0.1:8087/back/file/

############## thread-pool 配置 ##############
thread-pool:
  core-pool-size: 8 # 高通骁龙898采用的是三丛集架构，由一颗超大核（ARM Cortex X2）、三颗大核和四颗小核组成
  max-pool-size: 8
  queue-capacity: 60
  keep-alive-seconds: 60
  thread-name-prefix: Video-Task
  rejected-execution-handler: CallerRunsPolicy

############## schedule 配置 ##############
schedule:
  cron:
    downloadVideo: '0 0 0 * * ?'
    pushHlsVideoStreams: '0 0 0 * * ?'
    updateIpv4AndIpv6: '0 0 0 * * ?'

############## mybatis-plus 配置 (文档: https://baomidou.com/introduce/) ##############
mybatis-plus:
  # 指定 MyBatis Mapper 对应的 XML 文件位置。
  mapper-locations: classpath*:mapper/xml/*.xml
  # 在 Mapper 对应的 XML 文件中可以直接使用类名，无需使用全限定类名。
  type-aliases-package: com.example.videoweb.domain.entity
  # 启动时是否检查 MyBatis XML 文件的存在，默认不检查。
  check-config-location: false
  configuration:
    # log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      # 表前缀
      table-prefix: v_

############## springdoc 配置 (文档: https://openapi.apifox.cn/) ##############
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Access-Token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效，1天
  timeout: 86400 # 1天
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: 18000 # 5小时
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-32
  # 是否输出操作日志
  is-log: false
